name: flutter_lucide
description: Flutter package for Lucide Icons. Lucide is a free, open-source icon set with 1450+ icons. It's a fork of the popular Feather icon set.
version: 1.6.1
homepage: https://lucide.dev/
repository: https://github.com/ravikovind/flutter_lucide
issue_tracker: https://github.com/ravikovind/flutter_lucide/issues

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: lucide
      fonts:
        - asset: lib/fonts/lucide.ttf

  uses-material-design: true

screenshots:
  - description: Lucide Logo
    path: screenshots/logo.png

topics:
  - lucide
  - lucide-icons
  - feather
  - feather-icons
  - icons
