name: script
description: simple script to convert old icon file to new icon file

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  path: ^1.8.0


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
